
spring:
  application:
    name: cards-publication


#here we put urls for all feign clients
users:
  ribbon:
    listOfServers: users:8080
# WARNING - You shoud replace localhost with the real IP , as locahost related to IP internal to docker
externalRecipients-url: "{\
           processAction: \"http://localhost:8090/test\", \
           api_test_externalRecipient1: \"http://localhost:8090/test\", \
           api_test_externalRecipient2: \"http://localhost:8090/test\" \
           }"

# WARNING : If you set this parameter to false , all users have the rights to respond to all cards
checkPerimeterForResponseCard: true
