
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/auth/realms/dev/protocol/openid-connect/certs
  data:
    mongodb:
      database: operator-fabric
      uri: mongodb://root:password@mongodb:27017/operator-fabric?authSource=admin&authMode=scram-sha1
server:
  forward-headers-strategy: framework
operatorfabric:
  security:
    oauth2:
      client-id: opfab-client
    jwt:
      login-claim: preferred_username
      expire-claim: exp
  businessLogActivated: true
  servicesUrls:
    users: "users:8080"
