version: '2.1'
services:
  mongodb:
    container_name: mongodb
    image: mongo:4.1.1-xenial
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
#      - "15674:15674"
  keycloak:
    container_name: keycloak
    image: jboss/keycloak:6.0.1
    command: -Dkeycloak.migration.action=import -Dkeycloak.migration.provider=dir -Dkeycloak.migration.dir=/realms/export
    environment:
    - KEYCLOAK_USER=admin
    - KEYCLOAK_PASSWORD=admin
    - DB_VENDOR=H2
    volumes:
    - ../realms:/realms
    ports:
    - "89:8080"
    - "90:9990"
  config:
    container_name: config
    depends_on:
     - rabbitmq
    image: "lfeoperatorfabric/of-configuration-cloud-service:1.1.0.RELEASE"
    user: ${USER_ID}:${USER_GID}
    ports:
     - "2000:8080"
     - "4000:5005"
    expose:
     - "8080"
    environment:
     - RABBITMQ_HOST=rabbitmq
     - RABBITMQ_PORT=5672
     - RABBITMQ_USER=guest
     - RABBITMQ_PASSWORD=guest
     - REGISTRY_HOST=registry
     - REGISTRY_PORT=8080
    volumes:
     - "../../../../src/main/docker/certificates:/certificates_to_add"
     - "../../../../services/infra/config/src/main/docker/volume/docker-configurations:/service-config"
  registry:
    container_name: registry
    depends_on:
     - config
    image: "lfeoperatorfabric/of-registry-cloud-service:1.1.0.RELEASE"
    user: ${USER_ID}:${USER_GID}
    ports:
     - "2001:8080"
     - "4001:5005"
    expose:
     - "8080"
    environment:
     - CONFIG_HOST=config
     - CONFIG_PORT=8080
    volumes:
      - "../../../../src/main/docker/certificates:/certificates_to_add"
  client_gateway:
    container_name: client_gateway
    depends_on:
     - registry
    image: "lfeoperatorfabric/of-client-gateway-cloud-service:1.1.0.RELEASE"
    user: ${USER_ID}:${USER_GID}
    ports:
     - "2002:8080"
     - "4002:5005"
    environment:
    - REGISTRY_HOST=registry
    - REGISTRY_PORT=8080
    - DEPENDS_ON=CONFIG
    volumes:
      - "../../../../src/main/docker/certificates:/certificates_to_add"
  users:
    container_name: users
    depends_on:
     - registry
    image: "lfeoperatorfabric/of-users-business-service:1.1.0.RELEASE"
    user: ${USER_ID}:${USER_GID}
    ports:
     - "2103:8080"
     - "4103:5005"
    environment:
    - REGISTRY_HOST=registry
    - REGISTRY_PORT=8080
    - DEPENDS_ON=CONFIG
    volumes:
      - "../../../../src/main/docker/certificates:/certificates_to_add"
  thirds:
    container_name: thirds
    depends_on:
     - registry
    image: "lfeoperatorfabric/of-thirds-business-service:1.1.0.RELEASE"
    user: ${USER_ID}:${USER_GID}
    ports:
     - "2100:8080"
     - "4100:5005"
    environment:
    - REGISTRY_HOST=registry
    - REGISTRY_PORT=8080
    - DEPENDS_ON=CONFIG
    volumes:
     - "../../../../src/main/docker/certificates:/certificates_to_add"
     - "../../../../services/core/thirds/src/main/docker/volume/thirds-storage:/thirds-storage"
  cards-publication:
    container_name: cards-publication
    depends_on:
     - registry
    image: "lfeoperatorfabric/of-cards-publication-business-service:1.1.0.RELEASE"
    user: ${USER_ID}:${USER_GID}
    ports:
     - "2102:8080"
     - "4102:5005"
    environment:
    - REGISTRY_HOST=registry
    - REGISTRY_PORT=8080
    - DEPENDS_ON=CONFIG
    volumes:
      - "../../../../src/main/docker/certificates:/certificates_to_add"
  cards-consultation:
    container_name: cards-consultation
    depends_on:
     - registry
    image: "lfeoperatorfabric/of-cards-consultation-business-service:1.1.0.RELEASE"
    user: ${USER_ID}:${USER_GID}
    ports:
     - "2104:8080"
     - "4104:5005"
    environment:
    - REGISTRY_HOST=registry
    - REGISTRY_PORT=8080
    - DEPENDS_ON=CONFIG
    volumes:
      - "../../../../src/main/docker/certificates:/certificates_to_add"
  actions:
    container_name: actions
    depends_on:
    - registry
    image: "lfeoperatorfabric/of-actions-business-service:1.1.0.RELEASE"
    user: ${USER_ID}:${USER_GID}
    ports:
    - "2105:8080"
    - "4105:5005"
    environment:
    - REGISTRY_HOST=registry
    - REGISTRY_PORT=8080
    - DEPENDS_ON=CONFIG
    volumes:
      - "../../../../src/main/docker/certificates:/certificates_to_add"
  web-ui:
    container_name: web-ui
    depends_on:
    - registry
    image: "lfeoperatorfabric/of-web-ui:1.1.0.RELEASE"
    user: ${USER_ID}:${USER_GID}
    ports:
    - "2200:8080"
    - "4200:5005"
    environment:
    - REGISTRY_HOST=registry
    - REGISTRY_PORT=8080
    - DEPENDS_ON=CONFIG
    volumes:
      - "../../../../src/main/docker/certificates:/certificates_to_add"
