apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: client-gateway-ingress
spec:
  rules:
    - host: you.opfab.host
      http:
        paths:
          - path: /
            backend:
              serviceName: client-gateway
              servicePort: 8080
