apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Adds namespace to all resources.
namespace: default

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# namePrefix: opfab-

# Labels to add to all resources and selectors.
commonLabels:
  app: lfeoperatorfabric

# Each entry in this list must resolve to an existing
# resource definition in YAML.  These are the resource
# files that kustomize reads, modifies and emits as a
# YAML string, with resources separated by document
# markers ("---").
resources:
  - cards-consultation-deployment.yaml
  - cards-consultation-service.yaml
  - cards-publication-deployment.yaml
  - cards-publication-service.yaml
  - client-gateway-deployment.yaml
  - client-gateway-service.yaml
  - client-gateway-ingress.yaml
  - config-deployment.yaml
  - config-service.yaml
  - oauth-deployment.yaml
  - oauth-service.yaml
  - registry-deployment.yaml
  - registry-service.yaml
  - thirds-deployment.yaml
  - thirds-persistentvolumeclaim.yaml
  - thirds-service.yaml
  - time-deployment.yaml
  - time-service.yaml
  - users-deployment.yaml
  - users-service.yaml
  - web-ui-deployment.yaml
  - web-ui-service.yaml

# Configuration files use for the application
configMapGenerator:
- name: service-config
  files:
  - ./configurations/application.yml
  - ./configurations/cards-consultation.yml
  - ./configurations/cards-publication.yml
  - ./configurations/client-gateway.yml
  - ./configurations/registry.yml
  - ./configurations/thirds.yml
  - ./configurations/time.yml
  - ./configurations/users.yml