server:
  port: 2002
spring:
  cloud:
    gateway:
      routes:
      - id: auth
        uri: http://localhost:89
        predicates:
        - Path=/auth/**
        filters:
        - RewritePath=/auth/token(?<path>.*), /auth/realms/dev/protocol/openid-connect/token$\{path}
        - RewritePath=/auth/code/(?<params>.*), /auth/realms/dev/protocol/openid-connect/auth?response_type=code&client_id=opfab-client&$\{params}
        - RewritePath=/auth/check_token, /auth/realms/dev/protocol/openid-connect/token/introspect
        - AddRequestHeader=Authorization, Basic b3BmYWItY2xpZW50Om9wZmFiLWtleWNsb2FrLXNlY3JldA==
      - id: actions
        uri: http://localhost:2105
        predicates:
        - Path=/actions/**
        filters:
        - RewritePath=/actions/(?<path>.*), /$\{path}
      - id: web-ui
        uri: http://localhost:2200
        predicates:
        - Path=/ui/**
        filters:
        - RewritePath=/ui/(?<path>.*), /$\{path}
      - id: thirds
        uri: http://localhost:2100
        predicates:
          - Path=/thirds/**
        filters:
          - RewritePath=/thirds/(?<path>.*), /thirds/$\{path}
# WARNING : THIS CORS CONFIGURATION SHOULD NOT BE USED IN PRODUCTION      
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "Authorization, Content-Type"
operatorfabric.gateway.configs:
  - web-ui.json
#logging.level.root: debug
