spring:
  profiles: registry-0
eureka:
  instance.hostname: registry-0
  client:
    serviceUrl.defaultZone: http://registry-0.registry:8080/eureka/,http://registry-1.registry:8080/eureka/
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
---
spring:
  profiles: registry-1
eureka:
  instance.hostname: registry-1
  client:
    serviceUrl.defaultZone: http://registry-0.registry:8080/eureka/,http://registry-1.registry:8080/eureka/
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0