eureka:
#  instance.hostname: registry
  client:
    serviceUrl.defaultZone: http://registry:8080/eureka/
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0