#  POPULATE THE USER DATABASE ON INIT 
# !!!! WARNNING: VALUES SHOULD BE CHANGED FOR PRODUCTION MODE !!!! 
# 
operatorfabric.users.default:
  users:
  - login: admin
    groups: ["ADMIN"]
    entities: ["ENTITY1","ENTITY2"]
  - login: rte-operator
    groups: ["RTE","ADMIN","TRANS"]
  - login: tso1-operator
    groups: ["TSO1","TRANS"]
    entities: ["ENTITY1"]
  - login: tso2-operator
    groups: ["TSO2", "TRANS"]
    entities: ["ENTITY2"]
  groups:
  - id: ADMIN
    name: ADMINISTRATORS
    description: The admin group
  - id: RTE
    name: RTE France
    description: RTE TSO Group
  - id: TSO1
    name: TSO number 1
    description: TSO 1 Group
  - id: TSO2
    name: TSO number 2
    description: TSO 2 Group
  - id: TSO3
    name: TSO number 3
    description: TSO 3 Group
  - id: TSO4
    name: TSO number 4
    description: TSO 4 Group
  - id: TRANS
    name: TRANS name
    description: Transnational Group
  entities:
  - id: ENTITY1
    name: Entity 1 name
    description: Entity 1 short description
  - id: ENTITY2
    name: Entity 2 name
    description: Entity 2 short description
  - id: ENTITY3
    name: Entity 3 name
    description: Entity 3 short description
  - id: ENTITY4
    name: Entity 4 name
    description: Entity 4 short description