operatorfabric:
  security:
    oauth2:
      flow:
        mode: CODE
        provider: Opfab Keycloak
        delagate-url: http://localhost:89/auth/realms/dev/protocol/openid-connect/auth?response_type=code&client_id=opfab-client
  feed:
    subscription:
      timeout: 600000
    card:
      time:
        display: BUSINESS
    timeline:
      domains:
        - "TR"
        - "J"
        - "7D"
        - "W"
        - "M"
        - "Y"
  archive:
    filters:
      publisher.list:
        - value: "TEST"
          label: "Test Publisher"
        - value: "TEST2"
          label: "Test Publisher 2"
      process.list:
        - process
        - someOtherProcess
      tags.list:
        - value: "tag1"
          label: "Label for tag 1"
        - value: "tag2"
          label: "Label for tag 2"
  i10n.supported.time-zones:
    - value: "Europe/Paris"
      label: "Headquarters timezone"
    - value: "Australia/Melbourne"
      label: "Down Under"
    - Europe/London
    - Europe/Dublin
    - Europe/Brussel
    - Europe/Berlin
    - Europe/Rome
    - Europe/Madrid
    - Europe/Lisbon
    - Europe/Amsterdam
    - Europe/Athens
    - Pacific/Samoa
  i18n.supported.locales:
  - en
  - fr
  settings:
    locale: en
    infos:
      description: true
